package com.amazonaws.samples;
import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

/**
 * The FeatureStats Object stores all the fields generated by the FeatureExtraction
 * class.
 * 
 * @author Vasilis Vryniotis <bbriniotis at datumbox.com>
 * @see <a href="http://blog.datumbox.com/developing-a-naive-bayes-text-classifier-in-java/">http://blog.datumbox.com/developing-a-naive-bayes-text-classifier-in-java/</a>
 */
public class WordStatistics implements Serializable{

	private static final long serialVersionUID = 1L;

	//Total number of views
    public int n;
    
    //Category and word appearance
    public Map<String, Map<String, Integer>> wordCategoryJointCount;
    
    //Count the number of times a category was found
    public Map<String, Integer> categoryCounts;

    
    public WordStatistics() {
        n = 0;
        this.wordCategoryJointCount = new HashMap<>();
        categoryCounts = new HashMap<>();
    }
}
